### ISSUE TITLE
random space between nickname and :

### ISSUE THREAD

**Issue by AqueleHaru** [abc123me/BetterForgeChat#12]
<img width="55" alt="image" src="https://github.com/abc123me/BetterForgeChat/assets/61639486/4e7a3110-8b66-48c8-938c-f0eec95fb63c">

**Comment by abc123me** [comment]
Can you include more information, something like a configuration file and a screenshot that isn't horribly clipped?

Also the output of the /bfc info command.

Issues like this are almost useless as there isn't enough information to do anything, if more information isn't provided I'll close the issue.

**Comment by AqueleHaru** [comment]
<img width="455" alt="image" src="https://github.com/abc123me/BetterForgeChat/assets/61639486/a3bb014c-840f-4ce9-bf11-e24b59e25e24">

cfg: https://hastebin.skyra.pw/afizezepoq.ini

**Comment by abc123me** [comment]
Thanks! What mod places the icons beside the username?

**Comment by AqueleHaru** [comment]
im using luck perms + custom resource pack with images replacing unicodes

**Comment by abc123me** [comment]
OK! I think I found your problem, in the config file try changing this:
```
	#  Controls the chat message format
	#    $prefix is replaced by the user's prefix or nothing if the user has no prefix
	#    $suffix is replaced by the user's suffix or nothing if the user has no suffix
	#    $name is replaced by the user's name, or nickname if they have one
	playerNameFormat = "$prefix $name $suffix"
	#  Controls the chat message format
	#    $time is replaced by the timestamp field or nothing if disabled
	#    $name is replaced by the user's name, or nickname if they have one
	#    $msg is replaced by the username's message (if you use it more then once it WILL break this mod)
	chatMessageFormat = "$name: $msg"
```
To this:
```
	#  Controls the chat message format
	#    $prefix is replaced by the user's prefix or nothing if the user has no prefix
	#    $suffix is replaced by the user's suffix or nothing if the user has no suffix
	#    $name is replaced by the user's name, or nickname if they have one
	playerNameFormat = "$prefix$name$suffix"
	#  Controls the chat message format
	#    $time is replaced by the timestamp field or nothing if disabled
	#    $name is replaced by the user's name, or nickname if they have one
	#    $msg is replaced by the username's message (if you use it more then once it WILL break this mod)
	chatMessageFormat = "$name: $msg"
```

(And restarting your server)

**Comment by AqueleHaru** [comment]
btw, is there a way to put the luckperms prefix on tab too?

**Comment by AqueleHaru** [comment]
> OK! I think I found your problem, in the config file try changing this:
> 
> ```
> 	#  Controls the chat message format
> 	#    $prefix is replaced by the user's prefix or nothing if the user has no prefix
> 	#    $suffix is replaced by the user's suffix or nothing if the user has no suffix
> 	#    $name is replaced by the user's name, or nickname if they have one
> 	playerNameFormat = "$prefix $name $suffix"
> 	#  Controls the chat message format
> 	#    $time is replaced by the timestamp field or nothing if disabled
> 	#    $name is replaced by the user's name, or nickname if they have one
> 	#    $msg is replaced by the username's message (if you use it more then once it WILL break this mod)
> 	chatMessageFormat = "$name: $msg"
> ```
> 
> To this:
> 
> ```
> 	#  Controls the chat message format
> 	#    $prefix is replaced by the user's prefix or nothing if the user has no prefix
> 	#    $suffix is replaced by the user's suffix or nothing if the user has no suffix
> 	#    $name is replaced by the user's name, or nickname if they have one
> 	playerNameFormat = "$prefix$name$suffix"
> 	#  Controls the chat message format
> 	#    $time is replaced by the timestamp field or nothing if disabled
> 	#    $name is replaced by the user's name, or nickname if they have one
> 	#    $msg is replaced by the username's message (if you use it more then once it WILL break this mod)
> 	chatMessageFormat = "$name: $msg"
> ```
> 
> (And restarting your server)

i will restart the server now.

**Comment by abc123me** [comment]
> btw, is there a way to put the luckperms prefix on tab too?

It should be automatic, however when updating the prefix sometimes a relog is needed for the change to take effect.

**Comment by AqueleHaru** [comment]
ok the space fixed, but, the prefix are not going to tab :(

**Comment by AqueleHaru** [comment]
im using fakename mod, is there a cause for the bug maybe?

**Comment by abc123me** [comment]
Try it without it, also, you need a permission enabled for tab list integration, please refer to the permissions list here:
https://github.com/abc123me/BetterForgeChat/wiki

**Comment by abc123me** [comment]
There are nicknames provided by BetterforgeChat, so there could be an issue with Fakename compatibility however I have not thoroughly tested it!

**Comment by AqueleHaru** [comment]
> Try it without it, also, you need a permission enabled for tab list integration, please refer to the permissions list here: https://github.com/abc123me/BetterForgeChat/wiki

what permissions should i enable or disable? im kinda confuse with docs

**Comment by abc123me** [comment]
Enable these two:
bfcmod.tablist.metadata
bfcmod.tablist.nickname

I'm guessing this is your first time running a MC server? (with plugins)

**Comment by AqueleHaru** [comment]
> Enable these two: bfcmod.tablist.metadata bfcmod.tablist.nickname
> 
> I'm guessing this is your first time running a MC server? (with plugins)

im using only mods. not plugins D: its forge pure server. i have 200 mods.

**Comment by AqueleHaru** [comment]
/lp group default permission set bfcmod.tablist.metadata true, thats it?

**Comment by abc123me** [comment]
> /lp group default permission set bfcmod.tablist.metadata true, thats it?



> > Enable these two: bfcmod.tablist.metadata bfcmod.tablist.nickname
> > I'm guessing this is your first time running a MC server? (with plugins)
> 
> im using only mods. not plugins D: its forge pure server. i have 200 mods.

That's what I meant :P MC1.18.2 is borked with no good way to run forge + plugins so you got to run PoS mods like this one to get a basic server going :/

**Comment by abc123me** [comment]
> /lp group default permission set bfcmod.tablist.metadata true, thats it?

Yeah, I don't think you need the true at the end, just giving it the node is enough.

**Comment by AqueleHaru** [comment]
<img width="201" alt="image" src="https://github.com/abc123me/BetterForgeChat/assets/61639486/29c76b05-787a-4489-869d-ded75b535e94">

Ok seems to be working.

last question, is there a way to hide the name? I want to use it for lore on server

and does /nick change the text above user heads too?

**Comment by abc123me** [comment]
I'm closing the original issue as completed however feel free to keep dicusssing the tab list, if it's not configuration related though I will direct you too make a new issue.

Is there a way to hide the name? Not that i'm aware of but if you provide more details maybe I could implement something like that for you.

Does /nick change the text above user heads too? I'm not sure, I'd have to test it, but I don't think it does. If it doesn't though I probably can make it do it.

**Comment by AqueleHaru** [comment]
hide the name on tab and above head. or only above head. thanks for the help. i really appreciate.

**Comment by abc123me** [comment]
Unfortunately you currently cannot do that with my mod, however if you make a new issue and tag it as an enhancement I'd be open to discuss adding the feature.

Also finally - Developer to developer here, please check the Wiki and read configuration files before creating issues on the GitHub, it's annoying to get emails about problems that could've been solved by just checking the Wiki :/
