### ISSUE TITLE
Nicknames not saving after server restart

### ISSUE THREAD

**Issue by Dashhound171** [abc123me/BetterForgeChat#15]
On my server, I have set everyones nicknames using the /nickfor command. It works and the nicknames work fine until the scheduled server restart every night. Then the next time I log on, the nicknames are gone and only the usernames apear. Is there a way to "save" the nicknames or fix this issue?

(Version 1.18.2)

**Comment by abc123me** [comment]
The nicknames should be saved, please attach your server's log files. Also commits with literally no other information then "feature X is not working" aren't useful, please include details like the mod configuration and server log files in any future commits you make, including on other repositories, it infuriates developers (such as myself) having to go back and forth unnecessarily about something that could've simply been resolved via sending a log file.

Thanks, Jeremiah Lowe
Python, C, Java, Linux developer
Data recovery, Repair, IT consulting
Independent contracting

**Comment by abc123me** [comment]
Ugh, CLO0SING this issue due to lack of any detail or actual explanation of the problem. Guessing you fixed it yourself.

Please do not post issues if you're not willing to actually provide information to solve the issue...
