### ISSUE TITLE
permission for porting to 1.20.1

### ISSUE THREAD

**Issue by Birbs-world** [abc123me/BetterForgeChat#16]
im wondering if i can have permission to port this over to 1.20.1 my self, im happy to do all the work necessary i just want your permission to use what you've done and work off that

**Comment by abc123me** [comment]
I will happily give you permission, and if you have any questions about the port I'd be happy to help. I just don't have time to setup a test server, eclipse, forge, gradle and all the other required crap.

Please submit any changes on the "main-1.20.x" branch as a GitHub pull request! You can also fork the project and work that way. I will maintain releases and update the curseforge.

I will give you credit for your work and don't mind giving you a considerable portion of future donations.

**Comment by Birbs-world** [comment]
thanks, it may take a bit, but ill get it done

**Comment by Birbs-world** [comment]
hey question, whats the best way to chat/communicate? i do have questions about how some of you code works (mainly the chat formating and color handeling) ive got the base components working and the luckperms and essentials intergrations working and tested in a development server as well as a server im running for me and some friends

**Comment by abc123me** [comment]
GitHub is good, if you create your own forked repository I will star and watch it. You can freely email me at `jeremiahbl@protonmail.com` for any in-depth or technical questions you might have.
