### ISSUE TITLE
hover/click events gets voided

### ISSUE THREAD

**Issue by ThirtyTwelveNor** [abc123me/BetterForgeChat#4]
Hello,
all hover or click events get voided from player messages
however it works fine if the "event" is not from a player message, 
for example join/leave message.
or commands

**Comment by abc123me** [comment]
Might not be able to do anything about this since BetterForgeChat is serverside only :(

**Comment by abc123me** [comment]
Nevermind, the mod is overwriting the Hover and Click events appended to the Component class. Will be fixed in version 1.2!

**Comment by abc123me** [comment]
See https://github.com/abc123me/BetterForgeChat/releases/tag/V1.2.0

**Comment by ThirtyTwelveNor** [comment]
@abc123me 
ok so this is an improvement. BUT this does not contain which specific text contains which chat event.

new problem=

Hello,
hover or click events get voided from player messages
because the default minecraft click/hover event 
covers/overrules the entire message.

intended mechanic=
minecraft ign click/hover event is only supposed to work on the "prefix" "ign" "suffix" text

this does work properly on say advancement messages

**Comment by abc123me** [comment]
Can you provide me some screenshots on the exact issue, some screenshots of what happens in vanilla MC and my mod, to be perfectly honest I am not at all familiar with the hover event and I assumed copying the hoverevent that vanilla MC creates and appending it to my code would fix the issue. As they say assumptions make an ass out of you & me!

**Comment by ThirtyTwelveNor** [comment]
https://youtu.be/71ygXJH3bbA
as you may see here. advancements works as intended, just messages that dont. should not be a hover event or a click event on the actual text a player writes. except if he actually writes something with a hoverevent(say like post item in chat :D)

**Comment by abc123me** [comment]
OK, That's gonna be a "PITA" to fix, I'll have to write a function to figure out what's a chat message and what's an item message and then respond with differing events accordingly. In the current system I may not be able to implement this but I'll give it some thought - don't expect a quick fix but for now this issue will be kept open and in the back of my mind.

**Comment by abc123me** [comment]
Doesn't look like chatting items in chat is a vanilla feature? Can you send me the mod you're using to do this. I am attempting to fix this issue but cannot adequately test it.

**Comment by ThirtyTwelveNor** [comment]
Hello
https://www.curseforge.com/minecraft/mc-mods/quark
but so there is no way to terminate all chat events between ign and suffix? then the ign chat events wouldnt cover the hover event of items...

maybe still a PITY but just a function between whats a prefix/ign/suffix and whats a player message?

**Comment by abc123me** [comment]
The termination issue will be fixed in the next release along with discord integration, however the custom hover events for sharing items is very complicated to implement.

**Comment by abc123me** [comment]
Closing this as fixed as of release V1.2.1, the plugin that you use to display items will not be supported until later due to requiring a level of extra programming complexity that I am unwilling to do. Not to mention the fact that adding it in could introduce lots of issues with other mods that use similar HoverEvents.

For now, you can create a separate issue requesting compatibility with quark but I'm tagging the core issue here (hover events not being properly terminated) as fixed.

https://github.com/abc123me/BetterForgeChat/releases/tag/V1.2.1

**Comment by abc123me** [comment]
You may be interested in playing with this release:
https://github.com/abc123me/BetterForgeChat/releases/tag/V1.3.0B

I'd be happy to have you do some bugtesting on it!
