### ISSUE TITLE
update to 1.19.2?

### ISSUE THREAD

**Issue by MykalsVapor** [abc123me/BetterForgeChat#9]
im a server owner and would like to use your mod on my Forge 1.19.2 Better Minecraft BMC3 modpack server.  any chance you could update it please?  thanks for making this :)
LuckPerms only recommends this mod for Forge....

**Comment by abc123me** [comment]
No

**Comment by MykalsVapor** [comment]
ruthless.... not even an explanation.  thanks anyway...

**Comment by abc123me** [comment]
I have my resons:
1. The need is very small as tools like SpongeForge allow typical server plugins with forge mods, SpongeForge exists for MC1.19.2, Fabric also exists, use one of those with a server plugin, Forge mods frankly aren't even really meant to manage chat and such - plugins are really what you should use anyway.
2. I don't want to maintain multiple versions of the mod, this mod was only intended to work with MC 1.18.2 as there are no plugin compatible servers that also operate with Forge.
3. Don't like the direction modern Minecraft is going, implementing features like chat reporting, blacklisting servers, ability to get permanently banned from singleplayer - this violates my libertarian principles, and I will not prop up Microsofts anti-consumer actions by creating mods for them no matter how niche.

**Comment by MykalsVapor** [comment]
thank you for the explanation :) i was using a fabric server but switched to forge for a specific mod.... seems you cant have everything you want, lol... i will probably go back to fabric.  i really do appreciate your response tho.  have a wonderful day.

**Comment by abc123me** [comment]
No problem, to be honest I barely have the time to maintain this mod, I was hoping putting it on github might bring in some people to fix some of the more annoying bugs and issues (like hover / chat events). I threw it together one weekend just for my personal server and once it got working enough for me and my friends I called it a day.

**Comment by AsrielFBI** [comment]
@abc123me SpongeForge is up to 1.16.5 only, where is the one you mention?

**Comment by abc123me** [comment]
I meant Fabric sorry :P

SpongeForge is more for versions below 1.18.2

Edit (addition):
I'm considering starting a MC server for my local university so I'm considering adding the 1.19.2 support. No promises though since modding MC has become far worse since the days of 1.7.10. Seems like after Microsoft bought it they've made it harder and harder to write mods, it's almost as annoying as the days of MC 1.2.5 now.

**Comment by nocturn9x** [comment]
Such a shame that Microsoft is making modding so difficult, especially considering it's what keeps their game alive. Thanks for your work, looking forward to a 1.19/1.20 port (no pressure though, as a developer myself I understand how hard these things are)

**Comment by abc123me** [comment]
Update about this: https://github.com/abc123me/BetterForgeChat/pull/18

Depending on how hard it is, it could happen, I will leave the issue as a wontfix item though.
